// This is an application for managing the way staff members go on leave in an organisation. It uses prototype oriented programming and test driven development.
const database = {
    staff: [],
    leaveRequest: []
}

// staff constructor function
function Staff(name, email) {
    this.name = name;
    this.email = email;
    // the staff Id will be autogenerated and will increment based on the Id of the most recent staff in the database
    this.staffId =
        (database.staff.length) ? database.staff[database.staff.length - 1].staffId + 1 : 1;
}

Staff.prototype.save = function () {
    database.staff.push(this);
}

// admin constructor function
function Admin(name, email) {
    Staff.call(this, name, email);
    this.isAdmin = true;  
}

Admin.prototype = Object.create(Staff.prototype);
Admin.prototype.constructor = Admin;

// leave-request constructor function
function LeaveRequest(duration, leaveType, staffId) {
    this.staffId = staffId;
    this.duration = duration;
    this.leaveType = leaveType;
    // the leaveRequest Id will be autogenerated and will increment based on the Id of the most recent leaveRequest in the database
    this.id =
        (database.leaveRequest.length) ? database.leaveRequest[database.leaveRequest.length - 1].id + 1 : 1;
    database.leaveRequest.push(this);
}

LeaveRequest.prototype.createRequest = function (duration, leaveType, staffId) {
    new LeaveRequest(duration, leaveType, staffId)
}

// Staff creates a request for leave
Staff.prototype.createRequest = function (duration, leaveType) {
    LeaveRequest.prototype.createRequest(duration, leaveType, staffId = this.staffId)
}

// Staff reads own leave request(s)
Staff.prototype.readOwnRequests = function () {
    let array = []
    for (let i = 0; i < database.leaveRequest.length; i++) {
        if (database.leaveRequest[i].staffId === this.staffId) {
            array.push(database.leaveRequest[i])
        }
    }
    if (array.length) return array;
    return 'staff has no leave request record!';
}

// Admin reads a leave request by leave id
Admin.prototype.readRequestById = function (id) {
    for (let i = 0; i < database.leaveRequest.length; i++) {
        if (database.leaveRequest[i].id === id) {
            return database.leaveRequest[i];
        }
    }
    return 'id not found!';
};

// Admin approves a leave request by id
Admin.prototype.approveRequest = function (id) {
    for (let i = 0; i < database.leaveRequest.length; i++) {
        if (database.leaveRequest[i].id === id) {
            database.leaveRequest[i].isApproved = true;
            return database.leaveRequest[i];
        }
    }
    return 'id not found!';
};

// Admin rejects a leave request by id
Admin.prototype.rejectRequest = function (id) {
    for (let i = 0; i < database.leaveRequest.length; i++) {
        if (database.leaveRequest[i].id === id) {
            database.leaveRequest[i].isApproved = false;
            return database.leaveRequest[i];
        }
    }
    return 'id not found!';
}

// Admin reads all leave requests history unique to staff by the staff id
Admin.prototype.readAllRequestsByStaffId = function (id) {
    let staffRequests = [];
    for (let i = 0; i < database.leaveRequest.length; i++) {
        if (database.leaveRequest[i].staffId === id) {
            staffRequests.push(database.leaveRequest[i])
        }
    }
    if (staffRequests.length) return staffRequests;
    return 'id not found!';
}

// Admin reads all leave requests in the database
Admin.prototype.readAllRequests = function () {
    return database.leaveRequest;
}

module.exports.database = database;
module.exports.Staff = Staff;
module.exports.Admin = Admin;
